export const strings = {
    "analyzing": "正在统计...",
    "stats": "🎉 统计信息\n加入的群组：{g} 个\n成员数：{u1} 人\n启用的群组：{e} 个\n成员数：{u2} 人",
    "welcome_private": "<b>欢迎使用 🎉</b>\n\n我可以：\n- 删除群成员以频道身份发送的消息\n- 删除匿名群管理的消息\n- 删除来自关联频道的消息\n- 解除频道消息在群内的置顶\n\n点击下面的按钮，将我添加至群组。\n\n源代码：<a href=\"https://github.com/AnotiaWang/AntiChannelSpammersBot\">GitHub</a>",
    "welcome_group": "欢迎使用！您可以发送 /on 或 /off 一键开启/关闭反马甲，或者发送 /config 进行详细的设置。用法详见 /help。",
    "add_to_group": "点此将我添加到群组",
    "group_only": "请在群组中使用。",
    "del_channel_message_on": "已在本群启用自动删除频道马甲发送的消息。\n\n您需要将我设置为管理员，并分配删除消息的权限。您可以发送 /config 查看相关设置，发送 /help 查看功能帮助。",
    "del_channel_message_off": "已停止自动删除频道马甲发送的消息。其它设置项未变，您可以在 /config 设置中更改。",
    "operator_not_admin": "<a href=\"tg://user?id={id}\">您</a>不是群主或管理员。",
    "help": "<b>🤖 使用帮助</b>\n\n<b> - /on | /off:</b> 启用 / 关闭自动删除\n\n<b> - /ban | /unban</b>: 封禁/解封马甲。被封禁后，对方无法使用任何马甲在本群发言。您也可以在群组设置里解封频道。\n\n<b> - /promote | /demote:</b> 将频道加入/移出白名单。支持将频道 UID (<code>-10012345678</code>) / username (<code>@YuanShen</code>) 作为参数，也可以回复一条消息来操作。\n\n<b> - /config:</b> 显示此群组的设置：\n    - 开关 “删除频道马甲的消息”；\n    - 开关 “删除群管匿名发送的消息”；\n    - 开关 “删除来自关联频道的消息”；\n    - 开关 “解除频道消息在群内置顶”；\n    - 查看和编辑白名单。\n\n本机器人基于 GPLv3 协议开源，源码发布于 <a href=\"https://github.com/AnotiaWang/AntiChannelSpammersBot\">GitHub</a>。",
    "x_added_to_whitelist": "已将 \"{x}\" ({id}) 添加到白名单。",
    "x_removed_from_whitelist": "已将 \"{x}\" ({id}) 从白名单中移除。",
    "x_already_in_whitelist": "该频道已在白名单中。",
    "x_not_in_whitelist": "该频道不在白名单中。",
    "x_not_a_channel": "目标不是频道，无法操作。",
    "get_channel_error": "查询失败：指定目标不是频道或不存在，请检查您的格式。请以频道 UID(如 <code>-123456789</code>) 或 username(@xxxx，对于公开频道) 作为命令参数。\n{code}",
    "command_usage_error": "请回复一条消息，或者使用 <code>[频道 UID/username]</code> 作为命令参数。",
    "whitelist_help": "<b>📃 白名单</b>\n\n点击按钮取消对应频道的授权。",
    "query_sender_not_admin": "您不是群主或管理员，再点我要摇人啦！\n\nPS：如果没有管理员权限，我可能无法获取群内成员权限组。",
    "reply_to_query": "请回复一条来自频道马甲的消息。",
    "ban_sender_chat_success": "已封禁频道 <code>{id}</code>，其所有者将无法在本群使用任何频道马甲。",
    "unban_sender_chat_success": "已解封频道 <code>{id}</code>。",
    "permission_error": "{x}失败，请检查您是否授予了我相应的权限，以及群内是否有提供类似功能的机器人。",
    "deleteMsgFailure": "尝试删除消息 (ID {id}) 失败！可能是我没有删除消息的权限，或者消息发送时间超过 48 小时。(15 秒后自毁)",
    "button_deleteMsg": "删除此消息",
    "settings": "<b>⚙️ 设置</b>",
    "ban_sender_chat": "封禁频道马甲",
    "unban_sender_chat": "解封频道马甲",
    "unpin_message": "解除消息置顶",
    "settings_saved": "设置成功",
    "pin_permission_needed": "请确保您已经授予我置顶消息的权限。",
    "exit_confirm": "请发送 <code>/exit Yes|Y</code> 确认退出",
    "save_success": "保存成功",
}